import type { Category, Currency } from './model'

// Stable seed IDs: append future categories instead of renumbering existing entries.
export const categories: Category[] = [
  {
    id: 'expense:0',
    name: '飲食',
    parentId: null,
    kind: 'expense',
    icon: 'food',
  },
  {
    id: 'expense:0:0',
    name: '早餐',
    parentId: 'expense:0',
    kind: 'expense',
    icon: 'food',
  },
  {
    id: 'expense:0:1',
    name: '午餐',
    parentId: 'expense:0',
    kind: 'expense',
    icon: 'food',
  },
  {
    id: 'expense:0:2',
    name: '晚餐',
    parentId: 'expense:0',
    kind: 'expense',
    icon: 'food',
  },
  {
    id: 'expense:0:3',
    name: '點心',
    parentId: 'expense:0',
    kind: 'expense',
    icon: 'food',
  },
  {
    id: 'expense:0:4',
    name: '飲料',
    parentId: 'expense:0',
    kind: 'expense',
    icon: 'food',
  },
  {
    id: 'expense:0:5',
    name: '酒類',
    parentId: 'expense:0',
    kind: 'expense',
    icon: 'food',
  },
  {
    id: 'expense:0:6',
    name: '水果',
    parentId: 'expense:0',
    kind: 'expense',
    icon: 'food',
  },
  {
    id: 'expense:1',
    name: '交通',
    parentId: null,
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:0',
    name: '加油費',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:1',
    name: '停車費',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:2',
    name: '火車',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:3',
    name: '捷運',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:4',
    name: '汽車',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:5',
    name: '計程車',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:6',
    name: '公車',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:7',
    name: '摩托車',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:8',
    name: '單車',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:9',
    name: '機票',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:10',
    name: '船票',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:11',
    name: '高鐵',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:1:12',
    name: '輕軌',
    parentId: 'expense:1',
    kind: 'expense',
    icon: 'transport',
  },
  {
    id: 'expense:2',
    name: '娛樂',
    parentId: null,
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:2:0',
    name: '電影',
    parentId: 'expense:2',
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:2:1',
    name: '遊樂園',
    parentId: 'expense:2',
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:2:2',
    name: '展覽',
    parentId: 'expense:2',
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:2:3',
    name: '影音',
    parentId: 'expense:2',
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:2:4',
    name: '音樂',
    parentId: 'expense:2',
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:2:5',
    name: '遊戲',
    parentId: 'expense:2',
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:2:6',
    name: '運動',
    parentId: 'expense:2',
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:2:7',
    name: '博弈',
    parentId: 'expense:2',
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:2:8',
    name: '消遣',
    parentId: 'expense:2',
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:2:9',
    name: '健身',
    parentId: 'expense:2',
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:2:10',
    name: '夜店',
    parentId: 'expense:2',
    kind: 'expense',
    icon: 'play',
  },
  {
    id: 'expense:3',
    name: '購物',
    parentId: null,
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:3:0',
    name: '市場',
    parentId: 'expense:3',
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:3:1',
    name: '衣物',
    parentId: 'expense:3',
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:3:2',
    name: '鞋子',
    parentId: 'expense:3',
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:3:3',
    name: '配件',
    parentId: 'expense:3',
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:3:4',
    name: '包包',
    parentId: 'expense:3',
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:3:5',
    name: '美妝保養',
    parentId: 'expense:3',
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:3:6',
    name: '精品',
    parentId: 'expense:3',
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:3:7',
    name: '禮物',
    parentId: 'expense:3',
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:3:8',
    name: '電子產品',
    parentId: 'expense:3',
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:3:9',
    name: '應用軟體',
    parentId: 'expense:3',
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:3:10',
    name: '襪子',
    parentId: 'expense:3',
    kind: 'expense',
    icon: 'bag',
  },
  {
    id: 'expense:4',
    name: '個人',
    parentId: null,
    kind: 'expense',
    icon: 'user',
  },
  {
    id: 'expense:4:0',
    name: '社交',
    parentId: 'expense:4',
    kind: 'expense',
    icon: 'user',
  },
  {
    id: 'expense:4:1',
    name: '通話費',
    parentId: 'expense:4',
    kind: 'expense',
    icon: 'user',
  },
  {
    id: 'expense:4:2',
    name: '借款',
    parentId: 'expense:4',
    kind: 'expense',
    icon: 'user',
  },
  {
    id: 'expense:4:3',
    name: '投資',
    parentId: 'expense:4',
    kind: 'expense',
    icon: 'user',
  },
  {
    id: 'expense:4:4',
    name: '稅金',
    parentId: 'expense:4',
    kind: 'expense',
    icon: 'user',
  },
  {
    id: 'expense:4:5',
    name: '保險',
    parentId: 'expense:4',
    kind: 'expense',
    icon: 'user',
  },
  {
    id: 'expense:4:6',
    name: '捐款',
    parentId: 'expense:4',
    kind: 'expense',
    icon: 'user',
  },
  {
    id: 'expense:4:7',
    name: '寵物',
    parentId: 'expense:4',
    kind: 'expense',
    icon: 'user',
  },
  {
    id: 'expense:4:8',
    name: '彩券',
    parentId: 'expense:4',
    kind: 'expense',
    icon: 'user',
  },
  {
    id: 'expense:4:9',
    name: '應用程式',
    parentId: 'expense:4',
    kind: 'expense',
    icon: 'user',
  },
  {
    id: 'expense:5',
    name: '醫療',
    parentId: null,
    kind: 'expense',
    icon: 'health',
  },
  {
    id: 'expense:5:0',
    name: '門診',
    parentId: 'expense:5',
    kind: 'expense',
    icon: 'health',
  },
  {
    id: 'expense:5:1',
    name: '牙醫保健',
    parentId: 'expense:5',
    kind: 'expense',
    icon: 'health',
  },
  {
    id: 'expense:5:2',
    name: '藥品',
    parentId: 'expense:5',
    kind: 'expense',
    icon: 'health',
  },
  {
    id: 'expense:5:3',
    name: '醫療用品',
    parentId: 'expense:5',
    kind: 'expense',
    icon: 'health',
  },
  {
    id: 'expense:5:4',
    name: '打針',
    parentId: 'expense:5',
    kind: 'expense',
    icon: 'health',
  },
  {
    id: 'expense:5:5',
    name: '住院',
    parentId: 'expense:5',
    kind: 'expense',
    icon: 'health',
  },
  {
    id: 'expense:5:6',
    name: '手術',
    parentId: 'expense:5',
    kind: 'expense',
    icon: 'health',
  },
  {
    id: 'expense:5:7',
    name: '健康檢查',
    parentId: 'expense:5',
    kind: 'expense',
    icon: 'health',
  },
  {
    id: 'expense:6',
    name: '家居',
    parentId: null,
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:0',
    name: '日常用品',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:1',
    name: '水費',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:2',
    name: '電費',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:3',
    name: '燃料費',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:4',
    name: '電話費',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:5',
    name: '網路費',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:6',
    name: '房租',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:7',
    name: '洗衣費',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:8',
    name: '修繕費',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:9',
    name: '家具',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:10',
    name: '訂閱',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:6:11',
    name: '家電',
    parentId: 'expense:6',
    kind: 'expense',
    icon: 'home',
  },
  {
    id: 'expense:7',
    name: '家庭',
    parentId: null,
    kind: 'expense',
    icon: 'heart',
  },
  {
    id: 'expense:7:0',
    name: '生活費',
    parentId: 'expense:7',
    kind: 'expense',
    icon: 'heart',
  },
  {
    id: 'expense:7:1',
    name: '教育',
    parentId: 'expense:7',
    kind: 'expense',
    icon: 'heart',
  },
  {
    id: 'expense:7:2',
    name: '看護',
    parentId: 'expense:7',
    kind: 'expense',
    icon: 'heart',
  },
  {
    id: 'expense:7:3',
    name: '玩具',
    parentId: 'expense:7',
    kind: 'expense',
    icon: 'heart',
  },
  {
    id: 'expense:7:4',
    name: '才藝',
    parentId: 'expense:7',
    kind: 'expense',
    icon: 'heart',
  },
  {
    id: 'expense:8',
    name: '生活',
    parentId: null,
    kind: 'expense',
    icon: 'sun',
  },
  {
    id: 'expense:8:0',
    name: '美容美髮',
    parentId: 'expense:8',
    kind: 'expense',
    icon: 'sun',
  },
  {
    id: 'expense:8:1',
    name: '泡湯',
    parentId: 'expense:8',
    kind: 'expense',
    icon: 'sun',
  },
  {
    id: 'expense:8:2',
    name: '按摩',
    parentId: 'expense:8',
    kind: 'expense',
    icon: 'sun',
  },
  {
    id: 'expense:8:3',
    name: '住宿',
    parentId: 'expense:8',
    kind: 'expense',
    icon: 'sun',
  },
  {
    id: 'expense:8:4',
    name: '旅行',
    parentId: 'expense:8',
    kind: 'expense',
    icon: 'sun',
  },
  {
    id: 'expense:8:5',
    name: '派對',
    parentId: 'expense:8',
    kind: 'expense',
    icon: 'sun',
  },
  {
    id: 'expense:9',
    name: '學習',
    parentId: null,
    kind: 'expense',
    icon: 'book',
  },
  {
    id: 'expense:9:0',
    name: '書籍',
    parentId: 'expense:9',
    kind: 'expense',
    icon: 'book',
  },
  {
    id: 'expense:9:1',
    name: '課程',
    parentId: 'expense:9',
    kind: 'expense',
    icon: 'book',
  },
  {
    id: 'expense:9:2',
    name: '教材',
    parentId: 'expense:9',
    kind: 'expense',
    icon: 'book',
  },
  {
    id: 'expense:9:3',
    name: '證書',
    parentId: 'expense:9',
    kind: 'expense',
    icon: 'book',
  },
  {
    id: 'expense:9:4',
    name: '探索',
    parentId: 'expense:9',
    kind: 'expense',
    icon: 'book',
  },
  {
    id: 'expense:9:5',
    name: '文具',
    parentId: 'expense:9',
    kind: 'expense',
    icon: 'book',
  },
  {
    id: 'expense:10',
    name: '投資',
    parentId: null,
    kind: 'expense',
    icon: 'chart',
  },
  {
    id: 'expense:10:0',
    name: '現股買進',
    parentId: 'expense:10',
    kind: 'expense',
    icon: 'chart',
  },
  {
    id: 'expense:10:1',
    name: '投資失利',
    parentId: 'expense:10',
    kind: 'expense',
    icon: 'chart',
  },
  {
    id: 'expense:11',
    name: '其他',
    parentId: null,
    kind: 'expense',
    icon: 'tag',
  },
  {
    id: 'expense:11:0',
    name: '對帳差額',
    parentId: 'expense:11',
    kind: 'expense',
    icon: 'tag',
  },
  {
    id: 'expense:11:1',
    name: '其他',
    parentId: 'expense:11',
    kind: 'expense',
    icon: 'tag',
  },
  {
    id: 'income:0',
    name: '薪水',
    parentId: null,
    kind: 'income',
    icon: 'income',
  },
  {
    id: 'income:1',
    name: '現股賣出',
    parentId: null,
    kind: 'income',
    icon: 'income',
  },
  {
    id: 'income:2',
    name: '現金股利',
    parentId: null,
    kind: 'income',
    icon: 'income',
  },
  {
    id: 'income:3',
    name: '獎金',
    parentId: null,
    kind: 'income',
    icon: 'income',
  },
  {
    id: 'income:4',
    name: '收款',
    parentId: null,
    kind: 'income',
    icon: 'income',
  },
  {
    id: 'income:5',
    name: '彩券',
    parentId: null,
    kind: 'income',
    icon: 'income',
  },
  {
    id: 'income:6',
    name: '利息',
    parentId: null,
    kind: 'income',
    icon: 'income',
  },
  {
    id: 'income:7',
    name: '對帳差額',
    parentId: null,
    kind: 'income',
    icon: 'income',
  },
  {
    id: 'income:8',
    name: '其他',
    parentId: null,
    kind: 'income',
    icon: 'income',
  },
  {
    id: 'transfer:0',
    name: '轉帳',
    parentId: null,
    kind: 'transfer',
    icon: 'transfer',
  },
  {
    id: 'transfer:1',
    name: '提款',
    parentId: null,
    kind: 'transfer',
    icon: 'transfer',
  },
  {
    id: 'transfer:2',
    name: '存款',
    parentId: null,
    kind: 'transfer',
    icon: 'transfer',
  },
  {
    id: 'transfer:3',
    name: '退款',
    parentId: null,
    kind: 'transfer',
    icon: 'transfer',
  },
  {
    id: 'transfer:4',
    name: '兌換',
    parentId: null,
    kind: 'transfer',
    icon: 'transfer',
  },
  {
    id: 'receivable:0',
    name: '借出',
    parentId: null,
    kind: 'receivable',
    icon: 'income',
  },
  {
    id: 'receivable:1',
    name: '代付',
    parentId: null,
    kind: 'receivable',
    icon: 'income',
  },
  {
    id: 'receivable:2',
    name: '報帳',
    parentId: null,
    kind: 'receivable',
    icon: 'income',
  },
  {
    id: 'payable:0',
    name: '借入',
    parentId: null,
    kind: 'payable',
    icon: 'income',
  },
  {
    id: 'payable:1',
    name: '信貸',
    parentId: null,
    kind: 'payable',
    icon: 'income',
  },
  {
    id: 'payable:2',
    name: '車貸',
    parentId: null,
    kind: 'payable',
    icon: 'income',
  },
  {
    id: 'payable:3',
    name: '房貸',
    parentId: null,
    kind: 'payable',
    icon: 'income',
  },
  {
    id: 'system:0',
    name: '手續費',
    parentId: null,
    kind: 'system',
    icon: 'income',
  },
  {
    id: 'system:1',
    name: '折扣',
    parentId: null,
    kind: 'system',
    icon: 'income',
  },
  {
    id: 'system:2',
    name: '紅利回饋',
    parentId: null,
    kind: 'system',
    icon: 'income',
  },
  {
    id: 'system:3',
    name: '利息支出',
    parentId: null,
    kind: 'system',
    icon: 'income',
  },
  {
    id: 'system:4',
    name: '利息收入',
    parentId: null,
    kind: 'system',
    icon: 'income',
  },
]

// Crypto precision is this product's posting policy, not a network identifier.
export const currencies: Currency[] = [
  {
    id: 'TWD',
    name: '新台幣',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'JPY',
    name: '日圓',
    precision: 0,
    type: 'fiat',
  },
  {
    id: 'CNY',
    name: '人民幣',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'USD',
    name: '美元',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'HKD',
    name: '港幣',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'EUR',
    name: '歐元',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'GBP',
    name: '英鎊',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'AUD',
    name: '澳幣',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'CAD',
    name: '加拿大幣',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'CHF',
    name: '瑞士法郎',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'SGD',
    name: '新加坡幣',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'NZD',
    name: '紐西蘭幣',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'KRW',
    name: '韓元',
    precision: 0,
    type: 'fiat',
  },
  {
    id: 'THB',
    name: '泰銖',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'VND',
    name: '越南盾',
    precision: 0,
    type: 'fiat',
  },
  {
    id: 'MYR',
    name: '馬來西亞令吉',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'IDR',
    name: '印尼盾',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'PHP',
    name: '菲律賓披索',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'INR',
    name: '印度盧比',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'AED',
    name: '阿聯酋迪拉姆',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'SAR',
    name: '沙烏地里亞爾',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'ZAR',
    name: '南非蘭特',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'SEK',
    name: '瑞典克朗',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'NOK',
    name: '挪威克朗',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'DKK',
    name: '丹麥克朗',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'PLN',
    name: '波蘭茲羅提',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'CZK',
    name: '捷克克朗',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'HUF',
    name: '匈牙利福林',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'TRY',
    name: '土耳其里拉',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'MXN',
    name: '墨西哥披索',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'BRL',
    name: '巴西雷亞爾',
    precision: 2,
    type: 'fiat',
  },
  {
    id: 'BTC',
    name: 'BTC',
    precision: 8,
    type: 'crypto',
  },
  {
    id: 'ETH',
    name: 'ETH',
    precision: 18,
    type: 'crypto',
  },
  {
    id: 'USDT',
    name: 'USDT',
    precision: 6,
    type: 'crypto',
  },
  {
    id: 'USDC',
    name: 'USDC',
    precision: 6,
    type: 'crypto',
  },
  {
    id: 'BNB',
    name: 'BNB',
    precision: 18,
    type: 'crypto',
  },
  {
    id: 'SOL',
    name: 'SOL',
    precision: 9,
    type: 'crypto',
  },
  {
    id: 'XRP',
    name: 'XRP',
    precision: 6,
    type: 'crypto',
  },
  {
    id: 'DOGE',
    name: 'DOGE',
    precision: 8,
    type: 'crypto',
  },
  {
    id: 'ADA',
    name: 'ADA',
    precision: 6,
    type: 'crypto',
  },
  {
    id: 'LTC',
    name: 'LTC',
    precision: 8,
    type: 'crypto',
  },
  {
    id: 'BCH',
    name: 'BCH',
    precision: 8,
    type: 'crypto',
  },
  {
    id: 'DOT',
    name: 'DOT',
    precision: 10,
    type: 'crypto',
  },
  {
    id: 'AVAX',
    name: 'AVAX',
    precision: 18,
    type: 'crypto',
  },
  {
    id: 'LINK',
    name: 'LINK',
    precision: 18,
    type: 'crypto',
  },
  {
    id: 'TRX',
    name: 'TRX',
    precision: 6,
    type: 'crypto',
  },
]
export const currency = (id: string) => {
  const found = currencies.find((c) => c.id === id)
  if (!found) throw new Error('未知幣種')
  return found
}
export const category = (id: string) => categories.find((c) => c.id === id)
export const categoryLabel = (id: string) => {
  const c = category(id)
  if (!c) return '未分類'
  const p = category(c.parentId ?? '')
  return p ? `${p.name}／${c.name}` : c.name
}
export const leafCategories = (kind: string) =>
  categories.filter((c) => c.kind === kind && !categories.some((child) => child.parentId === c.id))
